### ISSUE TITLE
Contribution to Blynk-MQTT-Samples

### ISSUE THREAD

**Issue by ahmedalkabir** [Blynk-Technologies/Blynk-MQTT-Samples#1]
Currently, I'm working on the project and I was thinking of using the MQTT protocol because of my experience in this protocol, Is it possible to contribute to this repo? 

@vshymanskyy

**Comment by vshymanskyy** [comment]
Hi. Thanks for your interest. What exactly would you like to contribute?

**Comment by ahmedalkabir** [comment]
well, I would like to improve the mqtt examples, especially the one based on the Arduino API.

**Comment by vshymanskyy** [comment]
Sure, you can propose your changes and send them for review using GitHub PR.
Are there any specific things you'd like to improve? The Arduino API example is rather polished

**Comment by ahmedalkabir** [comment]
As my project is based on esp32, I thought it would be nice to expand the example of Arduino to use FreeRTOS to create a sophisticated sample that can handle different stuff at once, even Arduino UNO R4 WiFi supports FreeRTOS out of the box.

**Comment by vshymanskyy** [comment]
Sure, feel free to create a new example based on FreeRTOS and submit it for review!
